In [1]:
# ==========================================
# CUSTOMER SUPPORT TICKET CLASSIFICATION
# STEP 1 : IMPORT LIBRARIES
# ==========================================

import warnings
warnings.filterwarnings("ignore")

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", None)

print("Libraries Imported Successfully")

Libraries Imported Successfully

In [2]:
# ==========================================
# STEP 2 : LOAD DATASET
# ==========================================

df = pd.read_csv("../data/customer_support_tickets.csv")

print("Dataset Loaded Successfully")

Dataset Loaded Successfully

In [3]:
# ==========================================
# STEP 3 : DATA EXPLORATION
# ==========================================

print("="*60)
print("FIRST FIVE RECORDS")
print("="*60)
display(df.head())

print("\nDataset Shape")
print(df.shape)

print("\nColumn Names")
print(df.columns.tolist())

print("\nInformation")
df.info()

print("\nMissing Values")
display(df.isnull().sum())

print("\nDuplicate Rows")
print(df.duplicated().sum())

============================================================
FIRST FIVE RECORDS
============================================================

,Ticket ID,Customer Name,Customer Email,Customer Age,Customer Gender,Product Purchased,Date of Purchase,Ticket Type,Ticket Subject,Ticket Description,Ticket Status,Resolution,Ticket Priority,Ticket Channel,First Response Time,Time to Resolution,Customer Satisfaction Rating
0,1,Marisa Obrien,carrollallison@example.com,32,Other,GoPro Hero,2021-03-22,Technical issue,Product setup,"I'm having an issue with the {product_purchased}. Please assist.\n\nYour billing zip code is: 71701.\n\nWe appreciate that you have requested a website address.\n\nPlease double check your email address. I've tried troubleshooting steps mentioned in the user manual, but the issue persists.",Pending Customer Response,NaN,Critical,Social media,2023-06-01 12:15:36,NaN,NaN
1,2,Jessica Rios,clarkeashley@example.com,42,Female,LG Smart TV,2021-05-22,Technical issue,Peripheral compatibility,"I'm having an issue with the {product_purchased}. Please assist.\n\nIf you need to change an existing product.\n\nI'm having an issue with the {product_purchased}. Please assist.\n\nIf The issue I'm facing is intermittent. Sometimes it works fine, but other times it acts up unexpectedly.",Pending Customer Response,NaN,Critical,Chat,2023-06-01 16:45:38,NaN,NaN
2,3,Christopher Robbins,gonzalestracy@example.com,48,Other,Dell XPS,2020-07-14,Technical issue,Network problem,"I'm facing a problem with my {product_purchased}. The {product_purchased} is not turning on. It was working fine until yesterday, but now it doesn't respond.\n\n1.8.3 I really I'm using the original charger that came with my {product_purchased}, but it's not charging properly.",Closed,Case maybe show recently my computer follow.,Low,Social media,2023-06-01 11:14:38,2023-06-01 18:05:38,3.0
3,4,Christina Dillon,bradleyolson@example.org,27,Female,Microsoft Office,2020-11-13,Billing inquiry,Account access,"I'm having an issue with the {product_purchased}. Please assist.\n\nIf you have a problem you're interested in and I'd love to see this happen, please check out the Feedback. I've already contacted customer support multiple times, but the issue remains unresolved.",Closed,Try capital clearly never color toward story.,Low,Social media,2023-06-01 07:29:40,2023-06-01 01:57:40,3.0
4,5,Alexander Carroll,bradleymark@example.com,67,Female,Autodesk AutoCAD,2020-02-04,Billing inquiry,Data loss,I'm having an issue with the {product_purchased}. Please assist.\n\n\nNote: The seller is not responsible for any damages arising out of the delivery of the battleground game. Please have the game in good condition and shipped to you I've noticed a sudden decrease in battery life on my {product_purchased}. It used to last much longer.,Closed,West decision evidence bit.,Low,Email,2023-06-01 00:12:42,2023-06-01 19:53:42,1.0

Dataset Shape
(8469, 17)

Column Names
['Ticket ID', 'Customer Name', 'Customer Email', 'Customer Age', 'Customer Gender', 'Product Purchased', 'Date of Purchase', 'Ticket Type', 'Ticket Subject', 'Ticket Description', 'Ticket Status', 'Resolution', 'Ticket Priority', 'Ticket Channel', 'First Response Time', 'Time to Resolution', 'Customer Satisfaction Rating']

Information
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8469 entries, 0 to 8468
Data columns (total 17 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Ticket ID                     8469 non-null   int64
 1   Customer Name                 8469 non-null   object
 2   Customer Email                8469 non-null   object
 3   Customer Age                  8469 non-null   int64
 4   Customer Gender               8469 non-null   object
 5   Product Purchased             8469 non-null   object
 6   Date of Purchase              8469 non-null   object
 7   Ticket Type                   8469 non-null   object
 8   Ticket Subject                8469 non-null   object
 9   Ticket Description            8469 non-null   object
 10  Ticket Status                 8469 non-null   object
 11  Resolution                    2769 non-null   object
 12  Ticket Priority               8469 non-null   object
 13  Ticket Channel                8469 non-null   object
 14  First Response Time           5650 non-null   object
 15  Time to Resolution            2769 non-null   object
 16  Customer Satisfaction Rating  2769 non-null   float64
dtypes: float64(1), int64(2), object(14)
memory usage: 1.1+ MB

Missing Values

Ticket ID                          0
Customer Name                      0
Customer Email                     0
Customer Age                       0
Customer Gender                    0
Product Purchased                  0
Date of Purchase                   0
Ticket Type                        0
Ticket Subject                     0
Ticket Description                 0
Ticket Status                      0
Resolution                      5700
Ticket Priority                    0
Ticket Channel                     0
First Response Time             2819
Time to Resolution              5700
Customer Satisfaction Rating    5700
dtype: int64

Duplicate Rows
0

In [4]:
# ==========================================
# STEP 4 : DATA CLEANING
# ==========================================

# Remove duplicate rows
df.drop_duplicates(inplace=True)

# Remove rows with missing values
df.dropna(inplace=True)

# Reset index
df.reset_index(drop=True, inplace=True)

print("Dataset Shape After Cleaning:", df.shape)

print("\nMissing Values:")
print(df.isnull().sum())

Dataset Shape After Cleaning: (2769, 17)

Missing Values:
Ticket ID                       0
Customer Name                   0
Customer Email                  0
Customer Age                    0
Customer Gender                 0
Product Purchased               0
Date of Purchase                0
Ticket Type                     0
Ticket Subject                  0
Ticket Description              0
Ticket Status                   0
Resolution                      0
Ticket Priority                 0
Ticket Channel                  0
First Response Time             0
Time to Resolution              0
Customer Satisfaction Rating    0
dtype: int64

In [5]:
# ==========================================
# STEP 6 : SELECT REQUIRED COLUMNS
# ==========================================

df = df[[
    "Ticket Description",
    "Ticket Type",
    "Ticket Priority"
]]

df.head()

,Ticket Description,Ticket Type,Ticket Priority
0,"I'm facing a problem with my {product_purchased}. The {product_purchased} is not turning on. It was working fine until yesterday, but now it doesn't respond.\n\n1.8.3 I really I'm using the original charger that came with my {product_purchased}, but it's not charging properly.",Technical issue,Low
1,"I'm having an issue with the {product_purchased}. Please assist.\n\nIf you have a problem you're interested in and I'd love to see this happen, please check out the Feedback. I've already contacted customer support multiple times, but the issue remains unresolved.",Billing inquiry,Low
2,I'm having an issue with the {product_purchased}. Please assist.\n\n\nNote: The seller is not responsible for any damages arising out of the delivery of the battleground game. Please have the game in good condition and shipped to you I've noticed a sudden decrease in battery life on my {product_purchased}. It used to last much longer.,Billing inquiry,Low
3,"I'm having an issue with the {product_purchased}. Please assist. 1-800-799-0808.\n\nProduct Search: What's New in 2-3-4-5? Report Feedback Customer Service is your best I'm using the original charger that came with my {product_purchased}, but it's not charging properly.",Cancellation request,High
4,"I'm having an issue with the {product_purchased}. Please assist.\n\n4. It is possible that we cannot find some type of text or a product name to identify someone like Mr. Brown.\n\n5. On the I've reviewed the troubleshooting steps on the official support website, but they didn't resolve the problem.",Product inquiry,High

In [6]:
# ==========================================
# STEP 7 : IMPORT NLP LIBRARIES
# ==========================================

import re
import nltk

from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

nltk.download('stopwords')
nltk.download('punkt')
nltk.download('wordnet')

stop_words = set(stopwords.words('english'))

lemmatizer = WordNetLemmatizer()

print("NLP Libraries Loaded")

NLP Libraries Loaded

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Nikhitha\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Nikhitha\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Nikhitha\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

In [7]:
# ==========================================
# STEP 8 : TEXT CLEANING FUNCTION
# ==========================================

def clean_text(text):

    text = str(text).lower()

    text = re.sub(r'http\S+', '', text)

    text = re.sub(r'[^a-zA-Z ]', '', text)

    words = nltk.word_tokenize(text)

    words = [word for word in words if word not in stop_words]

    words = [lemmatizer.lemmatize(word) for word in words]

    return " ".join(words)

In [8]:
# ==========================================
# STEP 9 : CLEAN TICKET DESCRIPTIONS
# ==========================================

df["Clean_Text"] = df["Ticket Description"].apply(clean_text)

df.head()

,Ticket Description,Ticket Type,Ticket Priority,Clean_Text
0,"I'm facing a problem with my {product_purchased}. The {product_purchased} is not turning on. It was working fine until yesterday, but now it doesn't respond.\n\n1.8.3 I really I'm using the original charger that came with my {product_purchased}, but it's not charging properly.",Technical issue,Low,im facing problem productpurchased productpurchased turning working fine yesterday doesnt respond really im using original charger came productpurchased charging properly
1,"I'm having an issue with the {product_purchased}. Please assist.\n\nIf you have a problem you're interested in and I'd love to see this happen, please check out the Feedback. I've already contacted customer support multiple times, but the issue remains unresolved.",Billing inquiry,Low,im issue productpurchased please assistif problem youre interested id love see happen please check feedback ive already contacted customer support multiple time issue remains unresolved
2,I'm having an issue with the {product_purchased}. Please assist.\n\n\nNote: The seller is not responsible for any damages arising out of the delivery of the battleground game. Please have the game in good condition and shipped to you I've noticed a sudden decrease in battery life on my {product_purchased}. It used to last much longer.,Billing inquiry,Low,im issue productpurchased please assistnote seller responsible damage arising delivery battleground game please game good condition shipped ive noticed sudden decrease battery life productpurchased used last much longer
3,"I'm having an issue with the {product_purchased}. Please assist. 1-800-799-0808.\n\nProduct Search: What's New in 2-3-4-5? Report Feedback Customer Service is your best I'm using the original charger that came with my {product_purchased}, but it's not charging properly.",Cancellation request,High,im issue productpurchased please assist product search whats new report feedback customer service best im using original charger came productpurchased charging properly
4,"I'm having an issue with the {product_purchased}. Please assist.\n\n4. It is possible that we cannot find some type of text or a product name to identify someone like Mr. Brown.\n\n5. On the I've reviewed the troubleshooting steps on the official support website, but they didn't resolve the problem.",Product inquiry,High,im issue productpurchased please assist possible find type text product name identify someone like mr brown ive reviewed troubleshooting step official support website didnt resolve problem

In [9]:
# ==========================================
# STEP 10 : LABEL ENCODING
# ==========================================

from sklearn.preprocessing import LabelEncoder

category_encoder = LabelEncoder()
priority_encoder = LabelEncoder()

df["Category"] = category_encoder.fit_transform(df["Ticket Type"])

df["Priority"] = priority_encoder.fit_transform(df["Ticket Priority"])

df.head()

,Ticket Description,Ticket Type,Ticket Priority,Clean_Text,Category,Priority
0,"I'm facing a problem with my {product_purchased}. The {product_purchased} is not turning on. It was working fine until yesterday, but now it doesn't respond.\n\n1.8.3 I really I'm using the original charger that came with my {product_purchased}, but it's not charging properly.",Technical issue,Low,im facing problem productpurchased productpurchased turning working fine yesterday doesnt respond really im using original charger came productpurchased charging properly,4,2
1,"I'm having an issue with the {product_purchased}. Please assist.\n\nIf you have a problem you're interested in and I'd love to see this happen, please check out the Feedback. I've already contacted customer support multiple times, but the issue remains unresolved.",Billing inquiry,Low,im issue productpurchased please assistif problem youre interested id love see happen please check feedback ive already contacted customer support multiple time issue remains unresolved,0,2
2,I'm having an issue with the {product_purchased}. Please assist.\n\n\nNote: The seller is not responsible for any damages arising out of the delivery of the battleground game. Please have the game in good condition and shipped to you I've noticed a sudden decrease in battery life on my {product_purchased}. It used to last much longer.,Billing inquiry,Low,im issue productpurchased please assistnote seller responsible damage arising delivery battleground game please game good condition shipped ive noticed sudden decrease battery life productpurchased used last much longer,0,2
3,"I'm having an issue with the {product_purchased}. Please assist. 1-800-799-0808.\n\nProduct Search: What's New in 2-3-4-5? Report Feedback Customer Service is your best I'm using the original charger that came with my {product_purchased}, but it's not charging properly.",Cancellation request,High,im issue productpurchased please assist product search whats new report feedback customer service best im using original charger came productpurchased charging properly,1,1
4,"I'm having an issue with the {product_purchased}. Please assist.\n\n4. It is possible that we cannot find some type of text or a product name to identify someone like Mr. Brown.\n\n5. On the I've reviewed the troubleshooting steps on the official support website, but they didn't resolve the problem.",Product inquiry,High,im issue productpurchased please assist possible find type text product name identify someone like mr brown ive reviewed troubleshooting step official support website didnt resolve problem,2,1

In [10]:
# ==========================================
# STEP 11 : TF-IDF
# ==========================================

from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(
    max_features=5000,
    ngram_range=(1,2)
)

X = tfidf.fit_transform(df["Clean_Text"])

y = df["Category"]

print(X.shape)

(2769, 5000)

In [11]:
# ==========================================
# STEP 12 : TRAIN TEST SPLIT
# ==========================================

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print(X_train.shape)
print(X_test.shape)

(2215, 5000)
(554, 5000)

In [12]:
# ==========================================
# STEP 13 : IMPORT ML MODELS
# ==========================================

from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import LinearSVC
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier

from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix
)

In [13]:
# ==========================================
# LOGISTIC REGRESSION
# ==========================================

lr = LogisticRegression(max_iter=1000, random_state=42)

lr.fit(X_train, y_train)

pred_lr = lr.predict(X_test)

print("="*50)
print("Logistic Regression")
print("="*50)

print("Accuracy :", accuracy_score(y_test, pred_lr))

print(classification_report(y_test, pred_lr))

==================================================
Logistic Regression
==================================================
Accuracy : 0.19855595667870035
              precision    recall  f1-score   support

           0       0.18      0.12      0.14       109
           1       0.17      0.12      0.14       103
           2       0.25      0.20      0.22       107
           3       0.18      0.19      0.18       119
           4       0.21      0.35      0.26       116

    accuracy                           0.20       554
   macro avg       0.20      0.20      0.19       554
weighted avg       0.20      0.20      0.19       554

In [14]:
# ==========================================
# MULTINOMIAL NAIVE BAYES
# ==========================================

nb = MultinomialNB()

nb.fit(X_train, y_train)

pred_nb = nb.predict(X_test)

print("="*50)
print("Multinomial Naive Bayes")
print("="*50)

print("Accuracy :", accuracy_score(y_test, pred_nb))

print(classification_report(y_test, pred_nb))

==================================================
Multinomial Naive Bayes
==================================================
Accuracy : 0.2111913357400722
              precision    recall  f1-score   support

           0       0.24      0.15      0.18       109
           1       0.22      0.09      0.12       103
           2       0.23      0.16      0.19       107
           3       0.18      0.25      0.21       119
           4       0.21      0.39      0.28       116

    accuracy                           0.21       554
   macro avg       0.22      0.21      0.20       554
weighted avg       0.22      0.21      0.20       554

In [15]:
# ==========================================
# LINEAR SVM
# ==========================================

svm = LinearSVC(random_state=42)

svm.fit(X_train, y_train)

pred_svm = svm.predict(X_test)

print("="*50)
print("Linear SVM")
print("="*50)

print("Accuracy :", accuracy_score(y_test, pred_svm))

print(classification_report(y_test, pred_svm))

==================================================
Linear SVM
==================================================
Accuracy : 0.2111913357400722
              precision    recall  f1-score   support

           0       0.21      0.18      0.20       109
           1       0.16      0.14      0.15       103
           2       0.24      0.22      0.23       107
           3       0.19      0.19      0.19       119
           4       0.24      0.31      0.27       116

    accuracy                           0.21       554
   macro avg       0.21      0.21      0.21       554
weighted avg       0.21      0.21      0.21       554

In [16]:
# ==========================================
# RANDOM FOREST
# ==========================================

rf = RandomForestClassifier(
    n_estimators=200,
    random_state=42
)

rf.fit(X_train, y_train)

pred_rf = rf.predict(X_test)

print("="*50)
print("Random Forest")
print("="*50)

print("Accuracy :", accuracy_score(y_test, pred_rf))

print(classification_report(y_test, pred_rf))

==================================================
Random Forest
==================================================
Accuracy : 0.17870036101083034
              precision    recall  f1-score   support

           0       0.17      0.12      0.14       109
           1       0.20      0.17      0.18       103
           2       0.15      0.13      0.14       107
           3       0.19      0.24      0.21       119
           4       0.18      0.23      0.20       116

    accuracy                           0.18       554
   macro avg       0.18      0.18      0.17       554
weighted avg       0.18      0.18      0.18       554

In [18]:
results = pd.DataFrame({
    "Model": [
        "Logistic Regression",
        "Naive Bayes",
        "Linear SVM",
        "Random Forest"
    ],
    "Accuracy": [
        accuracy_score(y_test, pred_lr),
        accuracy_score(y_test, pred_nb),
        accuracy_score(y_test, pred_svm),
        accuracy_score(y_test, pred_rf)
    ]
})

results = results.sort_values(by="Accuracy", ascending=False)
display(results)

                 Model  Accuracy
1          Naive Bayes  0.211191
2           Linear SVM  0.211191
0  Logistic Regression  0.198556
3        Random Forest  0.178700

In [19]:
print(df["Ticket Type"].value_counts())

Ticket Type
Refund request          596
Technical issue         580
Billing inquiry         544
Product inquiry         533
Cancellation request    516
Name: count, dtype: int64

In [20]:
print("Unique Ticket Types:", df["Ticket Type"].nunique())
print(df["Ticket Type"].unique())

Unique Ticket Types: 5
['Technical issue' 'Billing inquiry' 'Cancellation request'
 'Product inquiry' 'Refund request']

In [21]:
display(df[["Ticket Description", "Ticket Type", "Ticket Priority"]].head(15))

,Ticket Description,Ticket Type,Ticket Priority
0,"I'm facing a problem with my {product_purchased}. The {product_purchased} is not turning on. It was working fine until yesterday, but now it doesn't respond.\n\n1.8.3 I really I'm using the original charger that came with my {product_purchased}, but it's not charging properly.",Technical issue,Low
1,"I'm having an issue with the {product_purchased}. Please assist.\n\nIf you have a problem you're interested in and I'd love to see this happen, please check out the Feedback. I've already contacted customer support multiple times, but the issue remains unresolved.",Billing inquiry,Low
2,I'm having an issue with the {product_purchased}. Please assist.\n\n\nNote: The seller is not responsible for any damages arising out of the delivery of the battleground game. Please have the game in good condition and shipped to you I've noticed a sudden decrease in battery life on my {product_purchased}. It used to last much longer.,Billing inquiry,Low
3,"I'm having an issue with the {product_purchased}. Please assist. 1-800-799-0808.\n\nProduct Search: What's New in 2-3-4-5? Report Feedback Customer Service is your best I'm using the original charger that came with my {product_purchased}, but it's not charging properly.",Cancellation request,High
4,"I'm having an issue with the {product_purchased}. Please assist.\n\n4. It is possible that we cannot find some type of text or a product name to identify someone like Mr. Brown.\n\n5. On the I've reviewed the troubleshooting steps on the official support website, but they didn't resolve the problem.",Product inquiry,High
5,"I'm having an issue with the {product_purchased}. Please assist.\n\nProduct Name: TPUBASK3E3KQ0\n\n\nJoin Date: Oct 2007 Posts: 11,532\n\nQuote: I've recently updated the firmware of my {product_purchased}, and the issue started happening afterward. Could it be related to the update?",Billing inquiry,High
6,"I'm having an issue with the {product_purchased}. Please assist.\n\n- Acknowledgement: Thanks to Dan for the tip. When you purchase a new product from my store or from your local retailer, they will also provide I'm concerned about the security of my {product_purchased} and would like to ensure that my data is safe.",Product inquiry,Critical
7,"I'm having an issue with the {product_purchased}. Please assist.\n\nI'm having an issue with the product_purchased}. Please assist. Customer Reviewer: My Husband was able to take an order from Apple I've checked for any available software updates for my {product_purchased}, but there are none.",Refund request,Low
8,"I'm having an issue with the {product_purchased}. Please assist. Thank you.""\n\nA statement from the consumer group had been released by Microsoft late on Tuesday afternoon. ""The purchase of this product was made using a contract with I'm using the original charger that came with my {product_purchased}, but it's not charging properly.",Technical issue,Critical
9,"I'm having an issue with the {product_purchased}. Please assist. It's not possible to remove the missing content. I've already contacted customer support multiple times, but the issue remains unresolved.",Cancellation request,Medium
10,"I'm having an issue with the {product_purchased}. Please assist.\n\nThe seller has sold the item for $29.89. When we receive your replacement, we will exchange the item for a full refund or exchange immediately upon I've already contacted customer support multiple times, but the issue remains unresolved.",Technical issue,Medium
11,"I'm having an issue with the {product_purchased}. Please assist. We hope that every vendor takes the time it takes in to do the following: ""Remove the product from your account - notify consumers, call them, make their I'm concerned about the security of my {product_purchased} and would like to ensure that my data is safe.",Refund request,Critical
12,"I've recently set up my {product_purchased}, but it fails to connect to any available networks. What steps should I take to troubleshoot this issue? If you know the answer, please let me know.\n\nDo I I've noticed a sudden decrease in battery life on my {product_purchased}. It used to last much longer.",Cancellation request,High
13,"I'm having an issue with the {product_purchased}. Please assist.\n\n1. Do I need to purchase a refund?\n\nThere is a way to purchase a refund from ZEROHITS, but there's not a I'm unable to find the option to perform the desired action in the {product_purchased}. Could you please guide me through the steps?",Technical issue,Critical
14,"I'm facing a problem with my {product_purchased}. The {product_purchased} is not turning on. It was working fine until yesterday, but now it doesn't respond.\n\nIf I'd just switched to a The issue I'm facing is intermittent. Sometimes it works fine, but other times it acts up unexpectedly.",Billing inquiry,Critical

In [7]:
import pandas as pd

df = pd.read_csv("../data/suport_customer_tickets.csv")

print("Shape:", df.shape)
print("\nColumns:")
print(df.columns.tolist())

display(df.head())
import pandas as pd

df = pd.read_csv("../data/suport_customer_tickets.csv")

print("Shape:", df.shape)
print("\nColumns:")
print(df.columns.tolist())

display(df.head())

Shape: (93, 7)

Columns:
['tweet_id', 'author_id', 'inbound', 'created_at', 'text', 'response_tweet_id', 'in_response_to_tweet_id']

,tweet_id,author_id,inbound,created_at,text,response_tweet_id,in_response_to_tweet_id
0,119237,105834,True,Wed Oct 11 06:55:44 +0000 2017,@AppleSupport causing the reply to be disregar...,119236,NaN
1,119238,ChaseSupport,False,Wed Oct 11 13:25:49 +0000 2017,@105835 Your business means a lot to us. Pleas...,NaN,119239.0
2,119239,105835,True,Wed Oct 11 13:00:09 +0000 2017,@76328 I really hope you all change but I'm su...,119238,NaN
3,119240,VirginTrains,False,Tue Oct 10 15:16:08 +0000 2017,@105836 LiveChat is online at the moment - htt...,119241,119242.0
4,119241,105836,True,Tue Oct 10 15:17:21 +0000 2017,@VirginTrains see attached error message. I've...,119243,119240.0

Shape: (93, 7)

Columns:
['tweet_id', 'author_id', 'inbound', 'created_at', 'text', 'response_tweet_id', 'in_response_to_tweet_id']

,tweet_id,author_id,inbound,created_at,text,response_tweet_id,in_response_to_tweet_id
0,119237,105834,True,Wed Oct 11 06:55:44 +0000 2017,@AppleSupport causing the reply to be disregar...,119236,NaN
1,119238,ChaseSupport,False,Wed Oct 11 13:25:49 +0000 2017,@105835 Your business means a lot to us. Pleas...,NaN,119239.0
2,119239,105835,True,Wed Oct 11 13:00:09 +0000 2017,@76328 I really hope you all change but I'm su...,119238,NaN
3,119240,VirginTrains,False,Tue Oct 10 15:16:08 +0000 2017,@105836 LiveChat is online at the moment - htt...,119241,119242.0
4,119241,105836,True,Tue Oct 10 15:17:21 +0000 2017,@VirginTrains see attached error message. I've...,119243,119240.0

In [8]:
# Keep only inbound tweets (customer messages)
df = df[df["inbound"] == True].copy()

# Keep only the text column
df = df[["text"]].dropna()

df.reset_index(drop=True, inplace=True)

print(df.shape)
display(df.head())

(49, 1)

                                                text
0  @AppleSupport causing the reply to be disregar...
1  @76328 I really hope you all change but I'm su...
2  @VirginTrains see attached error message. I've...
3  @VirginTrains yep, I've tried laptop too sever...
4  @VirginTrains I still haven't heard &amp; the ...

In [9]:
import re

def assign_category(text):
    text = text.lower()

    if re.search(r"\b(refund|return|money back|reimburse)\b", text):
        return "Refund"

    elif re.search(r"\b(charged|payment|bill|invoice|transaction)\b", text):
        return "Billing"

    elif re.search(r"\b(cancel|cancellation|terminate|close account)\b", text):
        return "Cancellation"

    elif re.search(r"\b(error|crash|not working|issue|problem|unable|failed)\b", text):
        return "Technical"

    elif re.search(r"\b(product|availability|information|details|price)\b", text):
        return "Product Inquiry"

    else:
        return "Other"

In [10]:
df["Category"] = df["text"].apply(assign_category)

print(df["Category"].value_counts())

Category
Other        43
Technical     5
Refund        1
Name: count, dtype: int64

In [11]:
df = df[df["Category"] != "Other"].copy()

print(df.shape)
print(df["Category"].value_counts())

(6, 2)
Category
Technical    5
Refund       1
Name: count, dtype: int64

In [12]:
import pandas as pd

df = pd.read_csv("../data/support_customer_tickets.csv")

print("Shape:", df.shape)
print("\nColumns:")
print(df.columns.tolist())

display(df.head())
import pandas as pd

df = pd.read_csv("../data/support_customer_tickets.csv")

print("Shape:", df.shape)
print("\nColumns:")
print(df.columns.tolist())

display(df.head())

C:\Users\Nikhitha\AppData\Local\Temp\ipykernel_24792\2748854899.py:3: DtypeWarning: Columns (4,5,6,11,16) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../data/support_customer_tickets.csv")

Shape: (1282355, 18)

Columns:
['Date received', 'Product', 'Sub-product', 'Issue', 'Sub-issue', 'Consumer complaint narrative', 'Company public response', 'Company', 'State', 'ZIP code', 'Tags', 'Consumer consent provided?', 'Submitted via', 'Date sent to company', 'Company response to consumer', 'Timely response?', 'Consumer disputed?', 'Complaint ID']

,Date received,Product,Sub-product,Issue,Sub-issue,Consumer complaint narrative,Company public response,Company,State,ZIP code,Tags,Consumer consent provided?,Submitted via,Date sent to company,Company response to consumer,Timely response?,Consumer disputed?,Complaint ID
0,05/10/2019,Checking or savings account,Checking account,Managing an account,Problem using a debit or ATM card,NaN,NaN,NAVY FEDERAL CREDIT UNION,FL,328XX,Older American,NaN,Web,05/10/2019,In progress,Yes,NaN,3238275
1,05/10/2019,Checking or savings account,Other banking product or service,Managing an account,Deposits and withdrawals,NaN,NaN,BOEING EMPLOYEES CREDIT UNION,WA,98204,NaN,NaN,Referral,05/10/2019,Closed with explanation,Yes,NaN,3238228
2,05/10/2019,Debt collection,Payday loan debt,Communication tactics,Frequent or repeated calls,NaN,NaN,CURO Intermediate Holdings,TX,751XX,NaN,NaN,Web,05/10/2019,Closed with explanation,Yes,NaN,3237964
3,05/10/2019,"Credit reporting, credit repair services, or o...",Credit reporting,Incorrect information on your report,Old information reappears or never goes away,NaN,NaN,Ad Astra Recovery Services Inc,LA,708XX,NaN,NaN,Web,05/10/2019,Closed with explanation,Yes,NaN,3238479
4,05/10/2019,Checking or savings account,Checking account,Managing an account,Banking errors,NaN,NaN,ALLY FINANCIAL INC.,AZ,85205,NaN,NaN,Postal mail,05/10/2019,In progress,Yes,NaN,3238460

C:\Users\Nikhitha\AppData\Local\Temp\ipykernel_24792\2748854899.py:12: DtypeWarning: Columns (4,5,6,11,16) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../data/support_customer_tickets.csv")

Shape: (1282355, 18)

Columns:
['Date received', 'Product', 'Sub-product', 'Issue', 'Sub-issue', 'Consumer complaint narrative', 'Company public response', 'Company', 'State', 'ZIP code', 'Tags', 'Consumer consent provided?', 'Submitted via', 'Date sent to company', 'Company response to consumer', 'Timely response?', 'Consumer disputed?', 'Complaint ID']

,Date received,Product,Sub-product,Issue,Sub-issue,Consumer complaint narrative,Company public response,Company,State,ZIP code,Tags,Consumer consent provided?,Submitted via,Date sent to company,Company response to consumer,Timely response?,Consumer disputed?,Complaint ID
0,05/10/2019,Checking or savings account,Checking account,Managing an account,Problem using a debit or ATM card,NaN,NaN,NAVY FEDERAL CREDIT UNION,FL,328XX,Older American,NaN,Web,05/10/2019,In progress,Yes,NaN,3238275
1,05/10/2019,Checking or savings account,Other banking product or service,Managing an account,Deposits and withdrawals,NaN,NaN,BOEING EMPLOYEES CREDIT UNION,WA,98204,NaN,NaN,Referral,05/10/2019,Closed with explanation,Yes,NaN,3238228
2,05/10/2019,Debt collection,Payday loan debt,Communication tactics,Frequent or repeated calls,NaN,NaN,CURO Intermediate Holdings,TX,751XX,NaN,NaN,Web,05/10/2019,Closed with explanation,Yes,NaN,3237964
3,05/10/2019,"Credit reporting, credit repair services, or o...",Credit reporting,Incorrect information on your report,Old information reappears or never goes away,NaN,NaN,Ad Astra Recovery Services Inc,LA,708XX,NaN,NaN,Web,05/10/2019,Closed with explanation,Yes,NaN,3238479
4,05/10/2019,Checking or savings account,Checking account,Managing an account,Banking errors,NaN,NaN,ALLY FINANCIAL INC.,AZ,85205,NaN,NaN,Postal mail,05/10/2019,In progress,Yes,NaN,3238460

In [13]:
# Keep only inbound tweets (customer messages)
df = df[df["inbound"] == True].copy()

# Keep only the text column
df = df[["text"]].dropna()

df.reset_index(drop=True, inplace=True)

print(df.shape)
display(df.head())

KeyError: 'inbound'

In [1]:
# ==========================================
# CUSTOMER SUPPORT TICKET CLASSIFICATION
# STEP 1 : IMPORT LIBRARIES
# ==========================================

import warnings
warnings.filterwarnings("ignore")

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", None)

print("Libraries Imported Successfully")

Libraries Imported Successfully

In [3]:
# ==========================================
# STEP 2 : LOAD DATASET
# ==========================================

df = pd.read_csv("../data/support_customer_ticket.csv")

print("Dataset Loaded Successfully")

Dataset Loaded Successfully

In [4]:
# ==========================================
# STEP 3 : DATA EXPLORATION
# ==========================================

print("="*60)
print("FIRST FIVE RECORDS")
print("="*60)
display(df.head())

print("\nDataset Shape")
print(df.shape)

print("\nColumn Names")
print(df.columns.tolist())

print("\nInformation")
df.info()

print("\nMissing Values")
display(df.isnull().sum())

print("\nDuplicate Rows")
print(df.duplicated().sum())

============================================================
FIRST FIVE RECORDS
============================================================

,Document,Topic_group
0,connection with icon icon dear please setup icon per icon engineers please let other details needed thanks lead,Hardware
1,work experience user work experience user hi work experience student coming next his name much appreciate him duration thank,Access
2,requesting for meeting requesting meeting hi please help follow equipments cable pc cord plug,Hardware
3,reset passwords for external accounts re expire days hi ask help update passwords colleagues thank pm expire days importance high hi received about expiration please kindly help prolongation best regards pm expire days importance high dear expire days order change please follow steps prerequisites disable device credentials close active connected by cable machine note also follow steps detailed press ctrl alt delete same pops change item enter format enter enter newly chosen then re enter again submit displaying has changed os machine browse enter format enter gear icon top tight browser window enter enter newly chosen then re enter again save connected note complete resources granted once connected by cable browse tick want change after logging enter format enter log enter enter newly chosen then re enter again change clients suppliers about expire please touch person then communicate back encounter issues hesitate by accessing yours,Access
4,mail verification warning hi has got attached please addresses best regards monitoring analyst verification warning,Miscellaneous

Dataset Shape
(47837, 2)

Column Names
['Document', 'Topic_group']

Information
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 47837 entries, 0 to 47836
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Document     47837 non-null  object
 1   Topic_group  47837 non-null  object
dtypes: object(2)
memory usage: 747.6+ KB

Missing Values

Document       0
Topic_group    0
dtype: int64

Duplicate Rows
0

In [5]:
# ==========================================
# STEP 4 : DATA CLEANING
# ==========================================

# Remove duplicate rows
df.drop_duplicates(inplace=True)

# Remove rows with missing values
df.dropna(inplace=True)

# Reset index
df.reset_index(drop=True, inplace=True)

print("Dataset Shape After Cleaning:", df.shape)

print("\nMissing Values:")
print(df.isnull().sum())

Dataset Shape After Cleaning: (47837, 2)

Missing Values:
Document       0
Topic_group    0
dtype: int64

In [6]:
print(df.shape)
print(df.isnull().sum())
print(df['Topic_group'].value_counts())
print(df.duplicated(subset=['Document']).sum())

(47837, 2)
Document       0
Topic_group    0
dtype: int64
Topic_group
Hardware                 13617
HR Support               10915
Access                    7125
Miscellaneous             7060
Storage                   2777
Purchase                  2464
Internal Project          2119
Administrative rights     1760
Name: count, dtype: int64
0

In [7]:
import re
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

stop_words = set(stopwords.words('english'))

def clean_text(text):
    text = str(text).lower()
    text = re.sub(r'[^a-z\s]', '', text)          # keep only letters
    tokens = word_tokenize(text)
    tokens = [t for t in tokens if t not in stop_words and len(t) > 2]
    return " ".join(tokens)

df['clean_text'] = df['Document'].apply(clean_text)
df[['Document', 'clean_text']].head()

,Document,clean_text
0,connection with icon icon dear please setup icon per icon engineers please let other details needed thanks lead,connection icon icon dear please setup icon per icon engineers please let details needed thanks lead
1,work experience user work experience user hi work experience student coming next his name much appreciate him duration thank,work experience user work experience user work experience student coming next name much appreciate duration thank
2,requesting for meeting requesting meeting hi please help follow equipments cable pc cord plug,requesting meeting requesting meeting please help follow equipments cable cord plug
3,reset passwords for external accounts re expire days hi ask help update passwords colleagues thank pm expire days importance high hi received about expiration please kindly help prolongation best regards pm expire days importance high dear expire days order change please follow steps prerequisites disable device credentials close active connected by cable machine note also follow steps detailed press ctrl alt delete same pops change item enter format enter enter newly chosen then re enter again submit displaying has changed os machine browse enter format enter gear icon top tight browser window enter enter newly chosen then re enter again save connected note complete resources granted once connected by cable browse tick want change after logging enter format enter log enter enter newly chosen then re enter again change clients suppliers about expire please touch person then communicate back encounter issues hesitate by accessing yours,reset passwords external accounts expire days ask help update passwords colleagues thank expire days importance high received expiration please kindly help prolongation best regards expire days importance high dear expire days order change please follow steps prerequisites disable device credentials close active connected cable machine note also follow steps detailed press ctrl alt delete pops change item enter format enter enter newly chosen enter submit displaying changed machine browse enter format enter gear icon top tight browser window enter enter newly chosen enter save connected note complete resources granted connected cable browse tick want change logging enter format enter log enter enter newly chosen enter change clients suppliers expire please touch person communicate back encounter issues hesitate accessing
4,mail verification warning hi has got attached please addresses best regards monitoring analyst verification warning,mail verification warning got attached please addresses best regards monitoring analyst verification warning

In [8]:
def lemmatize(text):
    doc = nlp(text)
    return " ".join([token.lemma_ for token in doc])

df['clean_text'] = df['clean_text'].apply(lemmatize)

NameError: name 'nlp' is not defined

In [10]:
import spacy
nlp = spacy.load("en_core_web_sm")
print(nlp)

<spacy.lang.en.English object at 0x00000285167C55D0>

In [11]:
def lemmatize_batch(texts):
    lemmatized = []
    for doc in nlp.pipe(texts, batch_size=100, disable=["parser", "ner"]):
        lemmatized.append(" ".join([token.lemma_ for token in doc]))
    return lemmatized

df['clean_text'] = lemmatize_batch(df['clean_text'].tolist())

In [12]:
df[['Document', 'clean_text']].sample(5)

,Document,clean_text
13159,new starter confluence wednesday re workstation equipment si wednesday re attached merci head analysis tuesday pm hello please fill date thank administration officer,new starter confluence wednesday workstation equipment wednesday attach merci head analysis tuesday hello please fill date thank administration officer
44863,transfer documents to new sent friday re update transfer documents hello thank you for your unfortunately there still seem be access rights granted or there some other kind issue can be seen below have option upload documents thanks,transfer document new send friday update transfer document hello thank unfortunately still seem access right grant kind issue see option upload document thank
12744,access needed wednesday july pm hello guys writing kindly ask permissions download bb matching help let best regards developer blvd floor district,access need wednesday july hello guy write kindly ask permission download matching help let well regard developer blvd floor district
21756,for wednesday february pm hello please add related replace these incidents thanks lot,wednesday february hello please add related replace incident thank lot
29664,po wednesday pm po dear purchased received items galaxy subscription voce updated include device under user name link please add installing device thanks kind regards administrator,wednesday dear purchase receive item galaxy subscription voce update include device user name link please add instal device thank kind regard administrator

In [13]:
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer

X = df['clean_text']
y = df['Topic_group']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

print(X_train.shape, X_test.shape)

(38269,) (9568,)

In [14]:
tfidf = TfidfVectorizer(max_features=5000, ngram_range=(1,2), min_df=2)

X_train_tfidf = tfidf.fit_transform(X_train)
X_test_tfidf = tfidf.transform(X_test)

print(X_train_tfidf.shape)

(38269, 5000)

In [15]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import classification_report, accuracy_score

nb = MultinomialNB()
nb.fit(X_train_tfidf, y_train)

y_pred_nb = nb.predict(X_test_tfidf)

print("Accuracy:", accuracy_score(y_test, y_pred_nb))
print(classification_report(y_test, y_pred_nb))

Accuracy: 0.7773829431438127
                       precision    recall  f1-score   support

               Access       0.87      0.79      0.83      1425
Administrative rights       0.93      0.32      0.48       352
           HR Support       0.83      0.76      0.80      2183
             Hardware       0.66      0.89      0.76      2724
     Internal Project       0.91      0.65      0.76       424
        Miscellaneous       0.76      0.73      0.74      1412
             Purchase       0.97      0.84      0.90       493
              Storage       0.93      0.71      0.80       555

             accuracy                           0.78      9568
            macro avg       0.86      0.71      0.76      9568
         weighted avg       0.80      0.78      0.78      9568

In [16]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC

lr = LogisticRegression(max_iter=1000, class_weight='balanced')
lr.fit(X_train_tfidf, y_train)
y_pred_lr = lr.predict(X_test_tfidf)
print("Logistic Regression Accuracy:", accuracy_score(y_test, y_pred_lr))
print(classification_report(y_test, y_pred_lr))

svm = LinearSVC(class_weight='balanced')
svm.fit(X_train_tfidf, y_train)
y_pred_svm = svm.predict(X_test_tfidf)
print("Linear SVM Accuracy:", accuracy_score(y_test, y_pred_svm))
print(classification_report(y_test, y_pred_svm))

Logistic Regression Accuracy: 0.8432274247491639
                       precision    recall  f1-score   support

               Access       0.90      0.88      0.89      1425
Administrative rights       0.63      0.84      0.72       352
           HR Support       0.89      0.83      0.86      2183
             Hardware       0.86      0.78      0.82      2724
     Internal Project       0.77      0.93      0.85       424
        Miscellaneous       0.78      0.86      0.82      1412
             Purchase       0.91      0.90      0.90       493
              Storage       0.83      0.93      0.88       555

             accuracy                           0.84      9568
            macro avg       0.82      0.87      0.84      9568
         weighted avg       0.85      0.84      0.84      9568

Linear SVM Accuracy: 0.8475125418060201
                       precision    recall  f1-score   support

               Access       0.89      0.90      0.90      1425
Administrative rights       0.71      0.76      0.74       352
           HR Support       0.87      0.85      0.86      2183
             Hardware       0.84      0.80      0.82      2724
     Internal Project       0.80      0.91      0.85       424
        Miscellaneous       0.80      0.85      0.82      1412
             Purchase       0.88      0.90      0.89       493
              Storage       0.86      0.91      0.88       555

             accuracy                           0.85      9568
            macro avg       0.83      0.86      0.85      9568
         weighted avg       0.85      0.85      0.85      9568

In [23]:
high_priority_keywords = ['urgent', 'asap', 'immediately', 'critical', 
                            'not working', 'cannot access', 'system down', 'outage', 'blocked']
medium_priority_keywords = ['issue', 'problem', 'error', 'help', 'request']

def assign_priority(text):
    text = text.lower()
    if any(word in text for word in high_priority_keywords):
        return 'high'
    elif any(word in text for word in medium_priority_keywords):
        return 'medium'
    else:
        return 'low'

df['priority'] = df['Document'].apply(assign_priority)
print(df['priority'].value_counts())

priority
low       25099
medium    18988
high       3750
Name: count, dtype: int64

In [24]:
X_train_p, X_test_p, y_train_p, y_test_p = train_test_split(
    df['clean_text'], df['priority'], test_size=0.2, random_state=42, stratify=df['priority']
)

# reuse a fresh TF-IDF fit (don't reuse the category one - fit fresh on this split)
tfidf_priority = TfidfVectorizer(max_features=5000, ngram_range=(1,2), min_df=2)
X_train_p_tfidf = tfidf_priority.fit_transform(X_train_p)
X_test_p_tfidf = tfidf_priority.transform(X_test_p)

svm_priority = LinearSVC(class_weight='balanced')
svm_priority.fit(X_train_p_tfidf, y_train_p)

y_pred_p = svm_priority.predict(X_test_p_tfidf)
print("Priority Accuracy:", accuracy_score(y_test_p, y_pred_p))
print(classification_report(y_test_p, y_pred_p))

Priority Accuracy: 0.9641513377926422
              precision    recall  f1-score   support

        high       0.86      0.80      0.83       750
         low       0.97      0.99      0.98      5020
      medium       0.97      0.96      0.97      3798

    accuracy                           0.96      9568
   macro avg       0.93      0.92      0.93      9568
weighted avg       0.96      0.96      0.96      9568

In [25]:
def predict_ticket(text):
    cleaned = clean_text(text)
    cleaned = lemmatize_batch([cleaned])[0]
    
    category_features = tfidf.transform([cleaned])
    category = svm.predict(category_features)[0]
    
    priority_features = tfidf_priority.transform([cleaned])
    priority = svm_priority.predict(priority_features)[0]
    
    return {"category": category, "priority": priority}

# test it
sample_ticket = "My laptop won't turn on and I need it urgently for a client call tomorrow"
print(predict_ticket(sample_ticket))

{'category': 'Hardware', 'priority': 'high'}

In [26]:
import joblib

joblib.dump(svm, 'category_model.pkl')
joblib.dump(tfidf, 'category_vectorizer.pkl')
joblib.dump(svm_priority, 'priority_model.pkl')
joblib.dump(tfidf_priority, 'priority_vectorizer.pkl')

['priority_vectorizer.pkl']

In [21]:
import os
print(os.getcwd())

c:\Users\Nikhitha\Desktop\FUTURE_ML_02\notebooks